void test_fail(const char * const fmt, ...) __attribute__ ((format (printf, 1, 2)));

int test_multialloc(void);
int test_parser(void);
int test_geometry(void);
int test_state(void);
int test_popcount(void);
int test_grow(void);
int test_next_steps(void);
int test_calc_next_steps(void);
int test_game(void);
int test_first_one(void);
int test_nth_one_index(void);
int test_unstep(void);
int test_random_ai(void);
int test_rollout(void);
int test_multiallocator(void);
int test_allocn(void);
int test_mcts_init_free(void);
int test_simulate(void);
int test_get_3moves_0(void);
int test_get_3moves_1(void);
int test_get_3moves_2(void);
int test_get_3moves_3(void);
int test_all_3moves(void);
